### ISSUE TITLE
Revise the selection of plays for the corpus

### ISSUE THREAD

**Issue by cmil** [dracor-org/engdracor#34]
While some of the TEI documents in the corpus are not actually dramatic works (e.g. Shakespeare's poem [The Rape of Lucrece](https://github.com/dracor-org/epdracor/blob/main/tei/shakespeare-lucrece.xml), A93033), others represent collections of multiple works (e.g. [cavendish-plays.xml](https://github.com/dracor-org/epdracor/blob/main/tei/cavendish-plays.xml) or [jonson-the-works.xml](https://github.com/dracor-org/epdracor/blob/main/tei/jonson-the-works.xml)).

The individual documents should be examined and the selection should be revised.

See also https://github.com/dracor-org/epdracor/issues/2#issuecomment-1096508583.

**Comment by lucagiovannini7** [comment]
In the sheet "proposed for deletion" of the [ep_metadata_dates](https://docs.google.com/spreadsheets/d/1kGYxY8biDmNrn376wABOR1wNKeWAo3vx2jDqljaXa8o/edit#gid=851563306) document, there is an initial list of works I feel should be outside EPDraCor. Most of them are entertainments (hybrid genre with low dramatic share), plus three poems, a comedy whose text is incomplete and some collected works.

**Comment by cmil** [comment]
> In the sheet "proposed for deletion" of the [ep_metadata_dates](https://docs.google.com/spreadsheets/d/1kGYxY8biDmNrn376wABOR1wNKeWAo3vx2jDqljaXa8o/edit#gid=851563306) document, there is an initial list of works which I feel should be outside EPDraCor. Most of them are entertainments (hybrid genre with low dramatic share), plus three poems, a comedy whose text is incomplete and some collected works.

Who is going to make a decision about that? @peertrilcke?

**Comment by peertrilcke** [comment]
- As far as I can see, **entertainments** did not have speaker <sp> annotated in the Early Print XML either, right @lucagiovannini7? So they are missing an important element of a drama. Also, they don't have a fictional plot. So I would exclude them as well. 
- The **poems** should also be excluded. 
- **Incomplete plays** as well. 
- I would also exclude the **collected works** for now. Here, however, at the end of the works, you can think about modeling them again separately as individual XMLs.

Overall then: I agree with @lucagiovannini7's list.

**Comment by cmil** [comment]
Resolved in 452530989933bee7c725580f45bb4b6b35df8100.
