### ISSUE TITLE
Specifying licence

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/engdracor#53]
While the sources of EarlyPrint (TCP - EEBO/ECCO) are licensed under [CC0/public domain](https://creativecommons.org/publicdomain/zero/1.0/), the Early Print corpus itself is covered by a [Creative Commons Attribution-NonCommercial 3.0 Unported licence](http://creativecommons.org/licenses/by-nc/3.0/legalcode).

> You are free to:
> 
>     Share — copy and redistribute the material in any medium or format
>     Adapt — remix, transform, and build upon the material
>     The licensor cannot revoke these freedoms as long as you follow the license terms.
> 
> Under the following terms:
> 
>     Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made . You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
>     NonCommercial — You may not use the material for commercial purposes.

Under which licence should we release the texts in EnDraCor/EPDraCor?

**Comment by cmil** [comment]
Done in 667190637bd1ce0e8701c90e3e5c5a378920d837
